name: restaurant_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.11
  provider: ^6.1.1
  http: ^1.2.1
  sqflite: ^2.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  android_alarm_manager_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1

# Command for run flutter splash screen:
# dart run flutter_native_splash:create
flutter_native_splash:
  color: '#ffffff'
  image: assets/picture/splash.png

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/picture/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
